name: Hello Server CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 0-23 * * 1-6'  

env:
  FILE_NAME: hello-server

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Build for Linux
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for Linux
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    runs-on: ubuntu-latest
    needs: build-go  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Linux artifact
      uses: actions/download-artifact@v2
      with:
        name: linux
        path: ./linux
        
    - name: Execute run.sh
      run: source ./run.sh

  download-only-windows:
    runs-on: windows-latest
    needs: build-go  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Windows artifact
      uses: actions/download-artifact@v2
      with:
        name: windows
